#!/usr/bin/python
# coding: utf-8

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#   status-report - Gather status report data
#   Author: Petr Šplíchal <psplicha@redhat.com>
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#   Copyright (c) 2012 Red Hat, Inc. All rights reserved.
#
#   This copyrighted material is made available to anyone wishing
#   to use, modify, copy, or redistribute it subject to the terms
#   and conditions of the GNU General Public License version 2.
#
#   This program is distributed in the hope that it will be
#   useful, but WITHOUT ANY WARRANTY; without even the implied
#   warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
#   PURPOSE. See the GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public
#   License along with this program; if not, write to the Free
#   Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#   Boston, MA 02110-1301, USA.
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"""
Comfortably gather status report data (e.g. list of committed
changes) for given week, month, quarter, year or selected date
range. By default all available stats for this week are reported.
"""

from __future__ import unicode_literals, absolute_import

import sys
import kerberos
import optparse
import ConfigParser
from dateutil.relativedelta import relativedelta as delta

import status_report.utils as utils
from status_report.base import UserStats


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  Options
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

class Options(object):
    """ Command line options parser """

    def __init__(self):
        """ Prepare the parser. """
        self.parser = optparse.OptionParser(
            usage="status-report [last] [week|month|quarter|year] [opts]",
            description=__doc__.strip())

        # Time & user selection
        group = optparse.OptionGroup(self.parser, "Selection")
        group.add_option(
            "--email", dest="emails", default=[], action="append",
            help="User email address(es)")
        group.add_option(
            "--since",
            help="Start date in the YYYY-MM-DD format")
        group.add_option(
            "--until",
            help="End date in the YYYY-MM-DD format")
        self.parser.add_option_group(group)

        # Create sample stats and include all stats objects options
        utils.log.debug("Loading Sample Stats group to build Options")
        self.sample_stats = UserStats()
        self.sample_stats.add_option(self.parser)

        # Display mode
        group = optparse.OptionGroup(self.parser, "Display mode")
        group.add_option(
            "--format", default="text",
            help="Output style, possible values: text (default) or wiki")
        group.add_option(
            "--width", default=utils.Config().width, type="int",
            help="Maximum width of the report output (default: %default)")
        group.add_option(
            "--brief", action="store_true",
            help="Show brief summary only, do not list individual items")
        group.add_option(
            "--verbose", action="store_true",
            help="Include more details (like modified git directories)")
        group.add_option(
            "--total", action="store_true",
            help="Append total stats after listing individual users")
        group.add_option(
            "--merge", action="store_true",
            help="Merge stats of all users into a single report")
        group.add_option(
            "--debug", action="store_true",
            help="Turn on debugging output, do not catch exceptions")
        self.parser.add_option_group(group)

    def parse(self):
        """ Parse the options. """
        (opt, arg) = self.parser.parse_args()

        # Enable debugging output
        if opt.debug:
            utils.logging.set(utils.LOG_DEBUG)

        # Enable --all if no particular stat or group selected
        opt.all = not any([
            getattr(opt, stat.dest) or getattr(opt, group.dest)
            for group in self.sample_stats.stats
            for stat in group.stats])

        # Set the default user
        if not opt.emails:
            opt.emails = utils.Config().email

        # Time period handling
        if opt.since is None and opt.until is None:
            opt.since, opt.until, period = self.time_period(arg)
        else:
            opt.since = utils.Date(opt.since or "1993-01-01")
            opt.until = utils.Date(opt.until or "today")
            # Make the 'until' limit inclusive
            opt.until.date += delta(days=1)
            period = "given date range"
        # Validate the date range
        if not opt.since.date < opt.until.date:
            raise RuntimeError(
                "Invalid date range ({0} to {1})".format(
                    opt.since, opt.until.date - delta(days=1)))
        print(u"Status report for {0} ({1} to {2}).".format(
            period, opt.since, opt.until.date - delta(days=1)))

        # Finito
        utils.log.debug("Gathered options:")
        utils.log.debug('options = {0}'.format(opt))
        return opt

    @staticmethod
    def time_period(arg):
        """ Detect desired time period for the argument """
        since, until, period = None, None, None
        if "year" in arg:
            if "last" in arg:
                since, until = utils.Date.last_year()
                period = "the last fiscal year"
            else:
                since, until = utils.Date.this_year()
                period = "this fiscal year"
        elif "quarter" in arg:
            if "last" in arg:
                since, until = utils.Date.last_quarter()
                period = "the last quarter"
            else:
                since, until = utils.Date.this_quarter()
                period = "this quarter"
        elif "month" in arg:
            if "last" in arg:
                since, until = utils.Date.last_month()
                period = "the last month"
            else:
                since, until = utils.Date.this_month()
                period = "this month"
        else:
            if "last" in arg:
                since, until = utils.Date.last_week()
                period = "the last week"
            else:
                since, until = utils.Date.this_week()
                period = "this week"
        return since, until, period


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  Main
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

def main():
    """ Parse options, gather stats, show the results """
    try:
        # Parse options
        options = Options().parse()

        # Check for user email addresses (command line or config)
        users = [utils.User(email=email) for email in options.emails]
        if not users:
            raise utils.ConfigError("No user email provided")

        # Prepare team stats object for data merging
        team_stats = UserStats(options=options)
        if options.merge:
            utils.header("Total Report")
            utils.item("Users: {0}".format(len(users)), options=options)

        # Check individual user stats
        for user in users:
            if options.merge:
                utils.item(user, 1, options=options)
            else:
                utils.header(user)
            user_stats = UserStats(user=user, options=options)
            user_stats.check()
            team_stats.merge(user_stats)

        # Display merged team report
        if options.merge or options.total:
            if options.total:
                utils.header("Total Report")
            team_stats.show()

    except (utils.ConfigError, utils.ReportError) as error:
        utils.log.error(error)
        sys.exit(1)

    except kerberos.GSSError as error:
        utils.log.error("Kerberos authentication failed. Try kinit.")
        sys.exit(2)

    except ConfigParser.NoSectionError as error:
        utils.log.error(error)
        utils.log.error(
            "No email provided on the command line or in the config file")
        utils.info(
            "Create at least a minimum config file {0}:".format(utils.CONFIG))
        from getpass import getuser
        utils.info(
            '[general]\nemail = "My Name" <{0}@domain.com>'.format(getuser()))
        sys.exit(3)


if __name__ == "__main__":
    main()
